In [1]:
#importing relevant libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
a=pd.read_excel("D:\\DATA SCIENCE\\MACHINE LEARNING\\Data preprocessing\\Data Preprocessing Data File.xlsx")
a

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [3]:
os.getcwd()#get current working directory

'C:\\Users\\RAMYA'

In [4]:
os.chdir("D:\\DATA SCIENCE\\MACHINE LEARNING\\Data preprocessing\\")
df1 = pd.read_excel("Data Preprocessing Data File.xlsx")
df1

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [5]:
#importing data set
df1

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [6]:
#missing values treatment

In [7]:
#in numerical data
#missing value treatment - impute values
#salary --- mean
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
imputer = imputer.fit(df1.iloc[:,2:3])
imputer.transform(df1.iloc[:,2:3])

array([[72000.],
       [48000.],
       [54000.],
       [62250.],
       [64000.],
       [58000.],
       [52000.],
       [62250.],
       [83000.],
       [67000.]])

In [8]:
#age -- median
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')
imputer = imputer.fit(df1.iloc[:,1:2])
imputer.transform(df1.iloc[:,1:2])

array([[44.],
       [27.],
       [39.],
       [39.],
       [39.],
       [35.],
       [39.],
       [48.],
       [50.],
       [37.]])

In [9]:
#categorical data 
#country -- mode
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
imputer = imputer.fit(df1.iloc[:,0:1])
imputer.transform(df1.iloc[:,0:1])

array([['France '],
       ['France '],
       ['Germany '],
       ['Spain '],
       ['Germany '],
       ['France '],
       ['Spain '],
       ['France '],
       ['Germany '],
       ['France ']], dtype=object)

In [10]:
#age -- constant
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='constant',fill_value=34)
imputer = imputer.fit(df1.iloc[:,1:2])
imputer.transform(df1.iloc[:,1:2])

array([[44.],
       [27.],
       [34.],
       [39.],
       [34.],
       [35.],
       [39.],
       [48.],
       [50.],
       [37.]])

In [11]:
#again

In [12]:
x=df1.iloc[:,:-1].values
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [13]:
y=df1.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [14]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer = imputer.fit(x[:,0:1])
x [:,0:1]= imputer.transform(x[:,0:1])
print (x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' nan 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' nan 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=40)
imputer = imputer.fit(x[:,1:2])
x [:,1:2]= imputer.transform(x[:,1:2])
print (x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 40 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' 40 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:,2:3])
x [:,2:3]= imputer.transform(x[:,2:3])
print (x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 40 54000.0]
 ['Spain ' 39.0 62250.0]
 ['Germany ' 40 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 62250.0]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [17]:
x

array([['France ', 44.0, 72000.0],
       ['France ', 27.0, 48000.0],
       ['Germany ', 40, 54000.0],
       ['Spain ', 39.0, 62250.0],
       ['Germany ', 40, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, 62250.0],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [18]:
#encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(x[:,0:1])

D:\anaconda\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 1, 2, 1, 0, 2, 0, 1, 0])

In [19]:
#Label Encoding 
from sklearn.preprocessing import LabelEncoder
label_x = LabelEncoder()
x[:,0]= label_x.fit_transform(x[:,0])
print (x)

[[0 44.0 72000.0]
 [0 27.0 48000.0]
 [1 40 54000.0]
 [2 39.0 62250.0]
 [1 40 64000.0]
 [0 35.0 58000.0]
 [2 39.0 52000.0]
 [0 48.0 62250.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('one', OneHotEncoder(), [0])])
ct.fit_transform(x)

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('one', OneHotEncoder(), [0])], remainder='passthrough')
c=ct.fit_transform(x) 
print(c)

[[1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 40 54000.0]
 [0.0 0.0 1.0 39.0 62250.0]
 [0.0 1.0 0.0 40 64000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 39.0 52000.0]
 [1.0 0.0 0.0 48.0 62250.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [22]:
label_y = LabelEncoder()
y = label_y.fit_transform(y)
print (y)

[0 1 0 0 1 1 0 1 0 1]


In [23]:
#Standardization
from sklearn.preprocessing import StandardScaler
std_sca= StandardScaler()
x_STD = std_sca.fit_transform(x)
print (pd.DataFrame(x_STD))
x

          0         1         2
0 -0.896258  0.660861  1.002707
1 -0.896258 -2.079293 -1.465494
2  0.384111  0.016119 -0.848444
3  1.664479 -0.145067  0.000000
4  0.384111  0.016119  0.179973
5 -0.896258 -0.789809 -0.437077
6  1.664479 -0.145067 -1.054127
7 -0.896258  1.305603  0.000000
8  0.384111  1.627974  2.133965
9 -0.896258 -0.467438  0.488498


array([[0, 44.0, 72000.0],
       [0, 27.0, 48000.0],
       [1, 40, 54000.0],
       [2, 39.0, 62250.0],
       [1, 40, 64000.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 62250.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [24]:
#Normalization - MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
Nm_x= MinMaxScaler()
x_NOR = Nm_x.fit_transform(x)
print (pd.DataFrame(x_NOR))


     0         1         2
0  0.0  0.739130  0.685714
1  0.0  0.000000  0.000000
2  0.5  0.565217  0.171429
3  1.0  0.521739  0.407143
4  0.5  0.565217  0.457143
5  0.0  0.347826  0.285714
6  1.0  0.521739  0.114286
7  0.0  0.913043  0.407143
8  0.5  1.000000  1.000000
9  0.0  0.434783  0.542857


In [25]:
#Normalization 
from sklearn.preprocessing import Normalizer
Nm_x= Normalizer()
x_NOR = Nm_x.fit_transform(x)
print (pd.DataFrame(x_NOR))


          0         1    2
0  0.000000  0.000611  1.0
1  0.000000  0.000562  1.0
2  0.000019  0.000741  1.0
3  0.000032  0.000627  1.0
4  0.000016  0.000625  1.0
5  0.000000  0.000603  1.0
6  0.000038  0.000750  1.0
7  0.000000  0.000771  1.0
8  0.000012  0.000602  1.0
9  0.000000  0.000552  1.0


In [26]:
#Model Creation 
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split (x_NOR,y,test_size = 0.2)
print (pd.DataFrame(x_train), y_train)


          0         1    2
0  0.000012  0.000602  1.0
1  0.000016  0.000625  1.0
2  0.000000  0.000552  1.0
3  0.000000  0.000603  1.0
4  0.000019  0.000741  1.0
5  0.000000  0.000611  1.0
6  0.000032  0.000627  1.0
7  0.000000  0.000562  1.0 [0 1 1 1 0 0 0 1]
